USE ERP_system;
GO

CREATE TABLE payment_terms (
	payment_term_id INT PRIMARY KEY IDENTITY(1,1),
	payment_term_name VARCHAR(255) NOT NULL,
)

INSERT INTO payment_terms (payment_term_name)
VALUES 
('Letter of Credit'),
('Cash on delivery'),
('EOM (end of month)'),
('Advance payment'),
('Documents against payment'),
('Payment method (Cash)'),
('Paymment method (Credit/Debit card)'),
('Paymment method (Bank Transfers)'),
('Paymment method (Checks)'),
('Paymment method (Mobile Payments)'),
('Paymment method (Digital Wallets)'),
('Paymment method (Contactless Payments)'),
('Paymment method (Cryptocurrencies)'),
('Paymment method (Prepaid Cards)'),
('Paymment method (Cashiers Checks/Money Orders)'),
('Paymment method (Peer-to-Peer (P2P) Payments)'),
('Paymment method (Bill Payments Services)'),
('Invoice'),
('Net 30'),
('Open account');
GO

CREATE TABLE legal_forms (
	legal_form_id INT PRIMARY KEY IDENTITY(1,1),
	legal_form_name VARCHAR(255) NOT NULL, 
)

INSERT INTO legal_forms (legal_form_name)
VALUES
('Partnership'),
('Limited liability company'),
('Corporation'),
('Sole proprietorship'),
('Contract'),
('Company'),
('General partnership'),
('Loan agreement'),
('Purchase agreement');
GO

CREATE TABLE status (
	status_id INT PRIMARY KEY IDENTITY(1,1),
	status_name VARCHAR(255) NOT NULL,
	status_type VARCHAR(255) NOT NULL,
)

INSERT INTO status (status_name, status_type)
VALUES
('Active', 'User'),
('Inactive', 'User'),
('Disabled', 'User'),
('Active', 'Company'),
('Inactive', 'Company'),
('Disabled', 'Company'),
('In stock', 'Item'),
('Out of stock', 'Item'),
('Web active', 'Item'),
('Completed', 'Order'),
('Processing', 'Order'),
('Ordered', 'Order'),
('Cancelled', 'Order'),
('Pending', 'Order_payment'),
('Processed', 'Order_payment');
GO

CREATE TABLE user_roles (
	user_role_id INT PRIMARY KEY IDENTITY(1,1),
	user_role_name VARCHAR(255) NOT NULL,
)

INSERT INTO user_roles (user_role_name)
VALUES
('Employee'),
('Owner'),
('Supporter'),
('Developer');
GO

CREATE TABLE iso_country_code (
	iso_country_code_id INT PRIMARY KEY IDENTITY(1,1),
	country VARCHAR(255) NOT NULL,
	iso_country_code VARCHAR(2) NOT NULL,
)

INSERT INTO iso_country_code (country, iso_country_code)
VALUES
('Afghanistan', 'AF'),
('Albania', 'AL'),
('Algeria', 'DZ'),
('American Samoa', 'AS'),
('Andorra', 'AD'),
('Angola', 'AO'),
('Anguilla', 'AI'),
('Antarctica', 'AQ'),
('Antigua and Barbuda', 'AG'),
('Argentina', 'AR'),
('Armenia', 'AM'),
('Aruba', 'AW'),
('Australia', 'AU'),
('Austria', 'AT'),
('Azerbaijan', 'AZ'),
('Bahamas', 'BS'),
('Bahrain', 'BH'),
('Bangladesh', 'BD'),
('Barbados', 'BB'),
('Belarus', 'BY'),
('Belgium', 'BE'),
('Belize', 'BZ'),
('Benin', 'BJ'),
('Bermuda', 'BM'),
('Bhutan', 'BT'),
('Bolivia', 'BO'),
('Bonaire, Sint Eustatius and Saba', 'BQ'),
('Bosnia and Herzegovina', 'BA'),
('Botswana', 'BW'),
('Bouvet Island', 'BV'),
('Brazil', 'BR'),
('British Indian Ocean Territory', 'IO'),
('Brunei Darussalam', 'BN'),
('Bulgaria', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Cabo Verde', 'CV'),
('Cambodia', 'KH'),
('Cameroon', 'CM'),
('Canada', 'CA'),
('Cayman Islands', 'KY'),
('Central African Republic', 'CF'),
('Chad', 'TD'),
('Chile', 'CL'),
('China', 'CN'),
('Christmas Island', 'CX'),
('Cocos Islands', 'CC'),
('Colombia', 'CO'),
('Comoros', 'KM'),
('Congo', 'CG'),
('Congo (DRC)', 'CD'),
('Cook Islands', 'CK'),
('Costa Rica', 'CR'),
('Croatia', 'HR'),
('Cuba', 'CU'),
('Curaçao', 'CW'),
('Cyprus', 'CY'),
('Czechia', 'CZ'),
('Côte d´Ivoire', 'CI'),
('Denmark', 'DK'),
('Djibouti', 'DJ'),
('Dominica', 'DM'),
('Dominican Republic', 'DO'),
('Ecuador', 'EC'),
('Egypt', 'EG'),
('El Salvador', 'SV'),
('Equatorial Guinea', 'GQ'),
('Eritrea', 'ER'),
('Estonia', 'EE'),
('Eswatini', 'SZ'),
('Ethiopia', 'ET'),
('Falkland Islands', 'FK'),
('Faroe Islands', 'FO'),
('Fiji', 'FJ'),
('Finland', 'FI'),
('France', 'FR'),
('French Guiana', 'GF'),
('French Polynesia', 'PF'),
('French Southern Territories', 'TF'),
('Gabon', 'GA'),
('Gambia', 'GM'),
('Georgia', 'GE'),
('Germany', 'DE'),
('Ghana', 'GH'),
('Gibraltar', 'GI'),
('Greece', 'GR'),
('Greenland', 'GL'),
('Grenada', 'GD'),
('Guadeloupe', 'GP'),
('Guam', 'GU'),
('Guatemala', 'GT'),
('Guernsey', 'GG'),
('Guinea', 'GN'),
('Guinea-Bissau', 'GW'),
('Guyana', 'GY'),
('Haiti', 'HT'),
('Heard Island and McDonald Islands', 'HM'),
('Holy See', 'VA'),
('Honduras', 'HN'),
('Hong Kong', 'HK'),
('Hungary', 'HU'),
('Iceland', 'IS'),
('India', 'IN'),
('Indonesia', 'ID'),
('Iran', 'IR'),
('Iraq', 'IQ'),
('Ireland', 'IE'),
('Isle of Man', 'IM'),
('Israel', 'IL'),
('Italy', 'IT'),
('Jamaica', 'JM'),
('Japan', 'JP'),
('Jersey', 'JE'),
('Jordan', 'JO'),
('Kazakhstan', 'KZ'),
('Kenya', 'KE'),
('Kiribati', 'KI'),
('Korea (North)', 'KP'),
('Korea (South)', 'KR'),
('Kuwait', 'KW'),
('Kyrgyzstan', 'KG'),
('Laos', 'LA'),
('Latvia', 'LV'),
('Lebanon', 'LB'),
('Lesotho', 'LS'),
('Liberia', 'LR'),
('Libya', 'LY'),
('Liechtenstein', 'LI'),
('Lithuania', 'LT'),
('Luxembourg', 'LU'),
('Macao', 'MO'),
('Madagascar', 'MG'),
('Malawi', 'MW'),
('Malaysia', 'MY'),
('Maldives', 'MV'),
('Mali', 'ML'),
('Malta', 'MT'),
('Marshall Islands', 'MH'),
('Martinique', 'MQ'),
('Mauritania', 'MR'),
('Mauritius', 'MU'),
('Mayotte', 'YT'),
('Mexico', 'MX'),
('Micronesia (Federated States of)', 'FM'),
('Moldova (the Republic of)', 'MD'),
('Monaco', 'MC'),
('Mongolia', 'MN'),
('Montenegro', 'ME'),
('Montserrat', 'MS'),
('Morocco', 'MA'),
('Mozambique', 'MZ'),
('Myanmar', 'MM'),
('Namibia', 'NA'),
('Nauru', 'NR'),
('Nepal', 'NP'),
('Netherlands (the)', 'NL'),
('New Caledonia', 'NC'),
('New Zealand', 'NZ'),
('Nicaragua', 'NI'),
('Niger (the)', 'NE'),
('Nigeria', 'NG'),
('Niue', 'NU'),
('Norfolk Island', 'NF'),
('Northern Mariana Islands (the)', 'MP'),
('Norway', 'NO'),
('Oman', 'OM'),
('Pakistan', 'PK'),
('Palau', 'PW'),
('Palestine, State of', 'PS'),
('Panama', 'PA'),
('Papua New Guinea', 'PG'),
('Paraguay', 'PY'),
('Peru', 'PE'),
('Philippines (the)', 'PH'),
('Pitcairn', 'PN'),
('Poland', 'PL'),
('Portugal', 'PT'),
('Puerto Rico', 'PR'),
('Qatar', 'QA'),
('Republic of North Macedonia', 'MK'),
('Romania', 'RO'),
('Russian Federation (the)', 'RU'),
('Rwanda', 'RW'),
('Réunion', 'RE'),
('Saint Barthélemy', 'BL'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
('Saint Kitts and Nevis', 'KN'),
('Saint Lucia', 'LC'),
('Saint Martin (French part)', 'MF'),
('Saint Pierre and Miquelon', 'PM'),
('Saint Vincent and the Grenadines', 'VC'),
('Samoa', 'WS'),
('San Marino', 'SM'),
('Sao Tome and Principe', 'ST'),
('Saudi Arabia', 'SA'),
('Senegal', 'SN'),
('Serbia', 'RS'),
('Seychelles', 'SC'),
('Sierra Leone', 'SL'),
('Singapore', 'SG'),
('Sint Maarten (Dutch part)', 'SX'),
('Slovakia', 'SK'),
('Slovenia', 'SI'),
('Solomon Islands', 'SB'),
('Somalia', 'SO'),
('South Africa', 'ZA'),
('South Georgia and the South Sandwich Islands', 'GS'),
('South Sudan', 'SS'),
('Spain', 'ES'),
('Sri Lanka', 'LK'),
('Sudan (the)', 'SD'),
('Suriname', 'SR'),
('Svalbard and Jan Mayen', 'SJ'),
('Sweden', 'SE'),
('Switzerland', 'CH'),
('Syrian Arab Republic', 'SY'),
('Taiwan (Province of China)', 'TW'),
('Tajikistan', 'TJ'),
('Tanzania, United Republic of', 'TZ'),
('Thailand', 'TH'),
('Timor-Leste', 'TL'),
('Togo', 'TG'),
('Tokelau', 'TK'),
('Tonga', 'TO'),
('Trinidad and Tobago', 'TT'),
('Tunisia', 'TN'),
('Turkey', 'TR'),
('Turkmenistan', 'TM'),
('Turks and Caicos Islands (the)', 'TC'),
('Tuvalu', 'TV'),
('Uganda', 'UG'),
('Ukraine', 'UA'),
('United Arab Emirates (the)', 'AE'),
('United Kingdom of Great Britain and Northern Ireland (the)', 'GB'),
('United States Minor Outlying Islands (the)', 'UM'),
('United States of America (the)', 'US'),
('Uruguay', 'UY'),
('Uzbekistan', 'UZ'),
('Vanuatu', 'VU'),
('Venezuela (Bolivarian Republic of)', 'VE'),
('Viet Nam', 'VN'),
('Virgin Islands (British)', 'VG'),
('Virgin Islands (U.S.)', 'VI'),
('Wallis and Futuna', 'WF'),
('Western Sahara', 'EH'),
('Yemen', 'YE'),
('Zambia','ZM'),
('Zimbabwe', 'ZW'),
('Åland Islands', 'AX');
GO

CREATE TABLE currencies (
	currency_id INT PRIMARY KEY IDENTITY(1,1),
	currency_name VARCHAR(255) NOT NULL,
	currency_code VARCHAR(10) NOT NULL,
);
GO

INSERT INTO currencies (currency_name, currency_code)
VALUES
('United States Dollar', 'USD'),
('Euro', 'EUR'),
('Japanese Yen', 'JPY'),
('British Pound Sterling', 'GBP'),
('Australian Dollar', 'AUD'),
('Canadian Dollar', 'CAD'),
('Swiss Franc', 'CHF'),
('Chinese Yuan Renminbi', 'CNY'),
('Swedish Krona', 'SEK'),
('New Zealand Dollar', 'NZD'),
('Mexican Peso', 'MXN'),
('Singapore Dollar', 'SGD'),
('Hong Kong Dollar', 'HKD'),
('Norwegian Krone', 'NOK'),
('South Korean Won', 'KRW'),
('Turkish Lira', 'TRY'),
('Indian Rupee', 'INR'),
('Russian Ruble', 'RUB'),
('Brazilian Real', 'BRL'),
('South African Rand', 'ZAR'),
('Danish Krone', 'DKK'),
('Polish Zloty', 'PLN'),
('New Taiwan Dollar', 'TWD'),
('Thai Baht', 'THB'),
('Indonesian Rupiah', 'IDR'),
('Hungarian Forint', 'HUF'),
('Czech Koruna', 'CZK'),
('Israeli New Shekel', 'ILS'),
('Chilean Peso', 'CLP'),
('Philippine Peso', 'PHP'),
('United Arab Emirates Dirham', 'AED'),
('Colombian Peso', 'COP'),
('Saudi Riyal', 'SAR'),
('Malaysian Ringgit', 'MYR'),
('Romanian Leu', 'RON');
GO

CREATE TABLE promotion_codes (
	code_id INT PRIMARY KEY IDENTITY(1,1),
	code VARCHAR(255) NOT NULL,
	discount_percentage INT NOT NULL,
);
GO